on:
  push:
    branches: [main]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Build script
        run: ./scripts/buildprod.sh

      

      - name: Pre-requisites
        run: sudo apt-get install apt-transport-https ca-certificates gnupg curl

      - name: Install gcloud packages
        run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

      - name : Install google-cloud sdk 
        run: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

      - name: Install google-cloud-cli 
        run: sudo apt-get update && sudo apt-get install google-cloud-cli

      - name: Auth gcloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.NOTELY_GCP_SECRET }}"

      - name: Build image and submit
        run: gcloud builds submit --tag asia-south1-docker.pkg.dev/notely-431802/notely-ar-repo/notely:latest .
